version: "3.8"

services:
  # Servicio para el backend (Node.js)
  backend:
    build:
      context: ./bakend-terminal
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "4242:4242"
    environment:
      - NODE_ENV=production
      - STRIPE_API_KEY=sk_test_51PsIPgCFWnCYk0MCXXRzxfsOFZPUvTYJsjvrhh90XMwjSYhmd9iyVWimpTsPgr4qPrlEX1f4mgsz35UIKcSm5CfP00SUEBiTjr
      #- STRIPE_API_KEY=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
      - PORT=4242

  # Servicio para el frontend (React)
  frontend:
    build:
      context: ./stripe-terminal-js
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4242

networks:
  app-network:
    driver: bridge
